### ISSUE TITLE
hardcaml-bloop is incompatible with uutf 1.0.0

### ISSUE THREAD

**Issue by gasche** [ujamjar/hardcaml-bloop#1]
See the opam-repository pull request to update the metadata:

  https://github.com/ocaml/opam-repository/pull/8555

As a very first step, it would be nice to update the `opam` file in this repository to mirror this restriction. (This helps avoid the next release to also have the wrong metadata.) Medium-term, you may want to think of adapting the code and having a release for (uutf >= 1.0.0).

**Comment by andrewray** [comment]
I have constrained the opam file in this repository to `{uutf >= 1.0.0}` as per the updated conversation in ocaml/opam-repository#8555.

Thank you for the bug report.
